import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Image from "next/image";
import galaxy from "../assets/img/andromeda-galaxy_2.jpg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Le site de tom</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className="text-red-500">Salut tout le monde</p>
      <Link href="/user/about">Vers la page /user/about</Link>
      <Image src={galaxy} alt="galaxy" />
      <Image
        src={
          "https://res.cloudinary.com/lereacteur-apollo/image/upload/v1612196960/memes/145352061_2039993396143501_6453735664784158206_n_sk9iju.jpg"
        }
        width={80} // Ces dimensions déterminent la taille de l'image qui sera chargée
        height={50}
        alt={"apollo"}
      />
    </>
  );
}
